djtutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls1/', include('polls1.urls')),
    path('polls2/', include('polls2.urls')),
    path('polls3/', include('polls3.urls')),
    path('polls4/', include('polls4.urls')),
    path('admin/', admin.site.urls),
]

polls2/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

polls3/urls.py
from django.urls import path

from . import views

app_name = 'polls3'

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/owner
    path('owner', views.owner, name='owner'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls4/urls.py
from django.urls import path

from . import views

app_name = 'polls4'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('owner', views.owner, name='owner'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls1/models.py
from django.db import models

# Create your models here.

polls2/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls4/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

# from polls2.models import Question
# from polls2.models import Choice

polls2/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. Jane Instructor / 1ff1de77 is the polls index.")

polls3/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.

from django.http import HttpResponse

from polls2.models import Question
from django.template import loader

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def owner(request):
    return HttpResponse("Hello, world. Jane Instructor / 1ff1de77 is the polls owner.")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

polls4/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.views import generic

from django.urls import reverse

from polls2.models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls4/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls4/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls4/results.html'

def owner(request):
    return HttpResponse("Hello, world. Jane Instructor / 1ff1de77 is the polls owner.")

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls4/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls4:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls4/results.html', {'question': question})

polls3/templates/polls/detail.html
{{ question }}

polls3/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls3:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls4/templates/polls4/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls4:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls4/templates/polls4/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls4:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls4/templates/polls4/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls4:detail' question.id %}">Vote again?</a>